#!/bin/sh

echo "This script builds the 'sparkjwt' command"

rm -rf bin
mkdir bin
echo "#!/usr/bin/env node" >> bin/sparkjwt
cat lib/command.js >> bin/sparkjwt

echo "All done: 'sparkjwt' script created!"
echo "checking bin directory:"
ls bin/
