#!/usr/bin/env node

const debug = require('debug')('sparkjwt')

var program = require('commander')

program
    .version('v0.3.0')
    .description('Utility to request access tokens for Cisco Spark "Guest" users of a developer organization\n\
  note that the "guest" command is a shortcut to typing "issuer" then "request" commands')
    .command('guest [-os] <userid> <username>', 'returns a temporary access token for the specified "Guest" user and developer "Organization"', { isDefault: true })
    .command('issuer [-os] <userid> <username>', 'creates a reusable JWT "issuer" token for the specified user and organization')
    .command('request <issuer>', 'returns a temporary "Guest" access token from a JWT "issuer" token')
    //.command('check <token>', 'displays info about the specified token')
    .on('--help', function () {
        console.log('')
        console.log('  Examples:')
        console.log('')
        console.log('    $ sparkjwt guest 123456789 "John Doe" -o "org_id" -s "secret"')
        console.log('      4234324.45435435.543543543')
        console.log('')
        console.log('    or without the shortcut:')
        console.log('')
        console.log('    $ sparkjwt issuer 123456789 "John Doe" -o "org_id" -s "secret"')
        console.log('      12tre33.54343275.5456456745')
        console.log('    $ sparkjwt request "12tre33.54343275.5456456745"')
        console.log('      4234324.45435435.543543543')
    });    

program.parse(process.argv);
